[versions]
gradle-starter = "0.49.0"
gradle-kotlinter = "3.11.1"
google-agp = "7.2.2"
maven-kotlin = "1.7.10"
maven-junit = "5.9.0"
maven-junit4 = "4.13.2"
maven-assertj = "3.23.1"
google-androidx-core = "1.8.0"
google-androidx-annotation = "1.4.0"
google-gson = "2.9.1"
google-androidtest = "1.4.0"
google-androidtestext = "1.1.3"
google-espresso = "3.4.0"

[libraries]
starter-gradle = { module = "com.project.starter:android", version.ref = "gradle-starter" }
agp-gradle = { module = "com.android.tools.build:gradle", version.ref = "google-agp" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "maven-junit" }
junit4-core = { module = "junit:junit", version.ref = "maven-junit4" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "maven-assertj" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "maven-kotlin" }
androidx-core = { module = "androidx.core:core", version.ref = "google-androidx-core" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "google-androidx-annotation" }
gson = { module = "com.google.code.gson:gson", version.ref = "google-gson" }
androidtest-core = { module = "androidx.test:core", version.ref = "google-androidtest" }
androidtest-runner = { module = "androidx.test:runner", version.ref = "google-androidtest" }
androidtest-rules = { module = "androidx.test:rules", version.ref = "google-androidtest" }
androidtest-junitext = { module = "androidx.test.ext:junit-ktx", version.ref = "google-androidtestext" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "google-espresso" }

[plugins]
jmailen-kotlinter = { id = "org.jmailen.kotlinter", version.ref = "gradle-kotlinter" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "maven-kotlin" }
