[versions]
gradle-starter = "0.64.0"
gradle-pluginpublish = "1.2.1"
gradle-doctor = "0.8.1"
google-agp = "8.1.2"
maven-kotlin = "1.9.20"
maven-junit = "5.10.0"
maven-assertj = "3.24.2"
google-androidx-core = "1.12.0"
google-androidx-annotation = "1.7.0"
google-gson = "2.10.1"
google-androidtest = "1.5.0"
google-androidtestRunner = "1.5.2"
google-androidtestext = "1.1.5"
google-espresso = "3.5.1"
google-appcompat = "1.6.1"
google-material = "1.10.0"
google-coordinatorlayout = "1.2.0"

[libraries]
agp-gradle-impl = { module = "com.android.tools.build:gradle", version.ref = "google-agp" }
agp-gradle-api = { module = "com.android.tools.build:gradle-api", version.ref = "google-agp" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "maven-kotlin" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "maven-junit" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "maven-assertj" }
androidx-core = { module = "androidx.core:core", version.ref = "google-androidx-core" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "google-androidx-annotation" }
gson = { module = "com.google.code.gson:gson", version.ref = "google-gson" }
androidtest-core = { module = "androidx.test:core", version.ref = "google-androidtest" }
androidtest-runner = { module = "androidx.test:runner", version.ref = "google-androidtestRunner" }
androidtest-rules = { module = "androidx.test:rules", version.ref = "google-androidtest" }
androidtest-junitext = { module = "androidx.test.ext:junit-ktx", version.ref = "google-androidtestext" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "google-espresso" }
appcompat-core = { module = "androidx.appcompat:appcompat", version.ref = "google-appcompat" }
material-core = { module = "com.google.android.material:material", version.ref = "google-material" }
coordinatorlayout-core = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "google-coordinatorlayout" }

[plugins]
starter-config = { id = "com.starter.config", version.ref = "gradle-starter" }
starter-versioning = { id = "com.starter.versioning", version.ref = "gradle-starter" }
starter-library-kotlin = { id = "com.starter.library.kotlin", version.ref = "gradle-starter" }
starter-library-android = { id = "com.starter.library.android", version.ref = "gradle-starter" }
starter-application-android = { id = "com.starter.application.android", version.ref = "gradle-starter" }
gradle-pluginpublish = { id = "com.gradle.plugin-publish", version.ref = "gradle-pluginpublish" }
osacky-doctor = { id = "com.osacky.doctor", version.ref = "gradle-doctor" }
