[versions]
java-compile = "25"
gradle-starter = "0.94.0"
gradle-pluginpublish = "2.0.0"
google-agp = "9.0.0"
maven-kotlin = "2.3.10"
maven-junit = "6.0.2"
maven-assertj = "3.27.7"
maven-insetter = "0.6.1"
maven-binarycompatiblity = "0.18.1"
maven-kotlin-serialization = "1.10.0"
google-androidx-core = "1.17.0"
google-androidx-annotation = "1.9.1"
google-androidtest = "1.7.0"
google-androidtestRunner = "1.7.0"
google-androidtestext = "1.3.0"
google-espresso = "3.7.0"
google-appcompat = "1.7.1"
google-material = "1.13.0"
google-coordinatorlayout = "1.3.0"
google-testServices = "1.6.0"
maven-poko = "0.21.1"
maven-vanniktech = "0.36.0"

[libraries]
agp-gradle-api = { module = "com.android.tools.build:gradle-api", version.ref = "google-agp" }
agp-gradle-impl = { module = "com.android.tools.build:gradle", version.ref = "google-agp" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "maven-kotlin" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "maven-junit" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "maven-assertj" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "google-androidx-core" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "google-androidx-annotation" }
androidtest-core = { module = "androidx.test:core", version.ref = "google-androidtest" }
androidtest-runner = { module = "androidx.test:runner", version.ref = "google-androidtestRunner" }
androidtest-rules = { module = "androidx.test:rules", version.ref = "google-androidtest" }
androidtest-junitext = { module = "androidx.test.ext:junit-ktx", version.ref = "google-androidtestext" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "google-espresso" }
appcompat-core = { module = "androidx.appcompat:appcompat", version.ref = "google-appcompat" }
material-core = { module = "com.google.android.material:material", version.ref = "google-material" }
coordinatorlayout-core = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "google-coordinatorlayout" }
androidx-test-services = { module = "androidx.test.services:test-services", version.ref = "google-testServices" }
chrisbanes-insetter = { module = "dev.chrisbanes.insetter:insetter", version.ref = "maven-insetter" }
kotlinx-serialization-json-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "maven-kotlin-serialization" }
sksamuel-scrimage-core = "com.sksamuel.scrimage:scrimage-core:4.3.5"
dropbox-differ = "com.dropbox.differ:differ:0.3.0"
jetbrains-dokka = "org.jetbrains.dokka:dokka-gradle-plugin:2.1.0"
vanniktech-maven-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "maven-vanniktech" }

[plugins]
starter-config = { id = "com.starter.config", version.ref = "gradle-starter" }
starter-versioning = { id = "com.starter.versioning", version.ref = "gradle-starter" }
starter-library-kotlin = { id = "com.starter.library.kotlin", version.ref = "gradle-starter" }
starter-library-android = { id = "com.starter.library.android", version.ref = "gradle-starter" }
starter-application-android = { id = "com.starter.application.android", version.ref = "gradle-starter" }
gradle-pluginpublish = { id = "com.gradle.plugin-publish", version.ref = "gradle-pluginpublish" }
kotlinx-binarycompatibility = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "maven-binarycompatiblity" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "maven-kotlin" }
drewhamilton-poko = { id = "dev.drewhamilton.poko", version.ref = "maven-poko" }
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-vanniktech" }
